### ISSUE TITLE
Problem with cnvGWAS

### ISSUE THREAD

**Issue by ItahisaMR** [waldronlab/CNVRanger#21]
I am contacting you because I am following the CNVRanger manual called "Summarization and quantitative trait analysis of CNV ranges" but I am unable to complete the final GWAS. 

The problem is: 

> segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name, method.m.test="none")
Error: logical subscript contains NAs

I have checked all the input files and there are no NA values in any of them. 

I follow all the step without any problem, and with your files I can get the final results. I tried to make the GDS and import the LRR/BAF values, but an error ocurr "CNV.gds' has been created or opened."

Do you know which could be the problem?

I hope you can help me, thank you in advance!

**Comment by lgeistlinger** [comment]
Hi @ItahisaMR - thank you for contacting us. @viniciushdasilva can you comment?

**Comment by viniciushdasilva** [comment]
Hi @ItahisaMR, as you can run our example without problems I can think about the possible problems. (i) Your input is space instead tab delimited. (ii) you can be using an old version, then check with sessionInfo() if you are using the latest CNVRanger release. 

If none of this options help you, you can send me an email enclosing at least part of your input that allows me to reproduce your error. In this case please send the files to viniciushs@usp.br.

**Comment by ItahisaMR** [comment]
Thank you very much for the support. I have checked that the files are tabs delimited (all was ok) and updated both the CNVRanger (1.4.0) and R versions (4.0.0). Now I get another different error:

Error in .qqunifPlot(segs.pvalue.gr$MinPvalueAdjusted, auto.key = list(corner = c(0.95,  : 
  pvalue vector contains zeros, can't draw plot

I've tried with the first chromosome only and I have good results. I don't understand why the error appears when using the complete files and not using only one chromosome. The files are exactly the same, the file of one chromosome is a subset of the complete one.

What may be the problem now? Sorry for the troubles.

**Comment by viniciushdasilva** [comment]
Could you try to run your analysis again please with the latest version in github? I just included a line that might help to solve this error. Please let me know if the error persists. To install the current version here use:

BiocManager::install("waldronlab/CNVRanger")

**Comment by ItahisaMR** [comment]
The error persists, sorry. 

Error in .qqunifPlot(segs.pvalue.gr$MinPvalueAdjusted, auto.key = list(corner = c(0.95,  : 
  pvalue vector contains zeros, can't draw plot

**Comment by viniciushdasilva** [comment]
I think I need to take a look in your inputs. Could you please send to me a file input that may retrieve this error? Unfortunately, I am not sure how to explore the possible problems in another way.

**Comment by ItahisaMR** [comment]
Thank you very much! Now I'm exploring the files... maybe i can find the bad chromosome! 

Thank you for your time!

**Comment by lgeistlinger** [comment]
Does this mean that this issue has been resolved? I am closing this issue, feel free to reopen.

**Comment by SaraNara** [comment]
> Thank you very much! Now I'm exploring the files... maybe i can find the bad chromosome!
> 
> Thank you for your time!

@ItahisaMR I am getting a similar error with GWAS. Have you solved the problem? I have also tried the solution provided by @viniciushdasilva. Still, the problem persists. Any other suggestions?

**Comment by lgeistlinger** [comment]
Hi @SaraNara best not to comment on a closed issue, but rather reopen, or open a new issue. We have replaced PLINK support with R native linear models for CNV GWAS in CNVRanger_v1.8.0, so I believe this is a new issue. @viniciushdasilva can you have a look?

**Comment by viniciushdasilva** [comment]
Hi @SaraNara,

It seems that you are using the example provided in #25 with the `master` branch of the package (i.e. https://github.com/waldronlab/CNVRanger/tree/master). If you have installed directly from bioconductor, or the master branch, the #25 example is not valid. This example can be only used to the `dev` branch (https://github.com/waldronlab/CNVRanger/tree/dev). In the `master` branch the vignette examples should work just fine. 

You just need to venture yourself in the `dev` branch, using the example in #25, if you need linear mixed models with a relationship matrix. More info on why linear mixed models are not in the `master` branch yet can be found here in #27.

**Comment by SaraNara** [comment]
Dear @viniciushdasilva ;
Thank you for your reply. I have downloaded the CNVRanger from the Bioconductor.  So it is the master branch. Your example works fine with GWAS. When I am trying to run my data I am getting 2 following errors;

#phen.info <- setupCnvGWAS("example", cnv.out.loc=re, map.loc=map.loc)
**Error in setupCnvGWAS("example", cnv.out.loc = re, map.loc = map.loc) : The map should be unique. If multiple populations with different probe map use map.loc=NULL**

When I used the map file I got the above error. So I also tried the map.loc=NULL. Then I am getting the below error.

segs.pvalue.gr <- cnvGWAS(phen.info, method.m.test="none")
**Error in .qqunifPlot(segs.pvalue.gr$MinPvalueAdjusted, auto.key = list(corner = c(0.95,  : 
  pvalue vector contains zeros, can't draw plot**



Here are the codes that I used;
cnv.calls <-read.table("~/PHD_2/Data/3_CNV/data_analysis/1_Sep2020/CNV_Ranger/EBV_Allison/outfile/cnvrangerinputfile/CNVOut_final.txt", sep = "\t", header = TRUE)
head(cnv.calls)


## ----calls2grl----------------------------------------------------------------
cnv.calls <- GenomicRanges::makeGRangesListFromDataFrame(cnv.calls, 
                                                         split.field="sample.id", keep.extra.columns=TRUE)
sort(cnv.calls)

## ----phenoData----------------------------------------------------------------
#phen.loc <- file.path(data.dir, "Pheno.txt")
#phen.df <- read.delim(phen.loc, as.is=TRUE)
phen.df <-read.delim("~/PHD_2/Data/3_CNV/data_analysis/1_Sep2020/CNV_Ranger/EBV_Allison/outfile/cnvrangerinputfile/pheno_final.txt")
head(phen.df)

## ----importPhen---------------------------------------------------------------
re <- RaggedExperiment::RaggedExperiment(cnv.calls, colData=phen.df)
re

## ----map----------------------------------------------------------------------
map.loc <- read.delim("~/PHD_2/Data/3_CNV/data_analysis/1_Sep2020/CNV_Ranger/EBV_Allison/outfile/cnvrangerinputfile/map_final.txt")
head(map.loc)

## ----importPhenRagged---------------------------------------------------------
#phen.info <- setupCnvGWAS("example", cnv.out.loc=re, map.loc=map.loc)#Error in setupCnvGWAS("example", cnv.out.loc = re, map.loc = map.loc) : The map should be unique. If multiple populations with different probe map use map.loc=NULL

phen.info <- setupCnvGWAS("example", cnv.out.loc=re, map.loc=NULL)
phen.info

## ----Wdir---------------------------------------------------------------------
all.paths <- phen.info$all.paths
all.paths



## ----CNVGWA-------------------------------------------------------------------
segs.pvalue.gr <- cnvGWAS(phen.info, method.m.test="none")
segs.pvalue.gr
